gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
  cachebust: soft

# Site settings
title: LanzaHomes | Villa in Lanzarote
description: Villa Maxim, located on the stunning island of Lanzarote.
keywords: villa rental, lanzarote rental, holiday rental lanzarote, villa rental lanzarote, rental villas, lanzarote holiday villa

# Name of project on Github
baseurl: '/'

# Build settings
markdown: kramdown
